### ISSUE TITLE
User can search for the availability of a fish, bug, or sea creature by name

### ISSUE THREAD

**Issue by yunx2** [yunx2/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for the availability of a fish, bug, or sea creature by name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
After typing the name of a creature into the text box and clicking on the button, user will be shown whether or not the creature can be caught now 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a button element and text input to HTML skeleton
- [ ] add radio input to let user choose which category of creature they are looking for
- [ ] style  to match the 'look up' screen figma
- [ ] layout changes from 2 columns to 1 column; breakpoint at 600px width
- [ ] in JS file, add event handler to button. and create XHR object
        - [ ] hander function gets valued from text and radio inputs
        - [ ] handler concatenates values from input to base api endpoint to create endpoint for a specific creature
        - [ ] handler uses XHR object to send request to the endpoint
- [ ] write function that handles the response data and is called inside the button event handler
       - [ ] function uses data from response to check if the current month is one of the months when that creature is 
available
       - [ ] function should create a result element from the data in response (eg icon_uri, name, availability), and the results of the check in the previous step and attach it to DOM 
       - [ ] if response has the value of null, display appropriate message to user
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
