### ISSUE TITLE
Feature: User can view details by clicking on button

### ISSUE THREAD

**Issue by yunx2** [yunx2/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details by clicking on button

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user can click a button in the results view to see more information about the creature they searched for

To do this, need to create a new  'details' view; and create a function for swapping views.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-22 at 12 28 33 PM](https://user-images.githubusercontent.com/45185196/134409231-5a077cf3-6808-4197-96a0-edaa2a5fdd57.png)

![Screen Shot 2021-09-22 at 12 29 00 PM](https://user-images.githubusercontent.com/45185196/134409277-20ae4761-8b5d-46b9-9556-f42a1140697b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ]  work on details view layout
  - [ ]  layout needs to be responsive (aka look good on mobile size screens) because there's a lot of information that has to be displayed
  - [ ] there should be a breakpoint where information spread over 2 columns becomes 1 column
- [ ] write a function that switches between views
  - [ ] function should get all elements with a 'data-view' attribute, add the 'hidden'  class to all views that are not the current one; current view can be stored on data object
  - [ ] add event handler that switches to details view to details button,
- [ ] add a button to details view that brings user back to find view 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
