### ISSUE TITLE
Feature:  User can add a creature to a locally stored “to-catch” list

### ISSUE THREAD

**Issue by yunx2** [yunx2/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click a button on the 'result' or 'details' view to add a creature to the 'to-catch' list. List persists between page reloads

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a the 'to catch' view  for  user to view their to-catch list. Save to-catch list to local storage before unload. Get catch list information from local storage next time page is loaded
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-22 at 5 33 26 PM](https://user-images.githubusercontent.com/45185196/134439473-6d0c49f7-d357-4743-b1fa-0de5d07f7b32.png)

![Screen Shot 2021-09-22 at 5 33 48 PM](https://user-images.githubusercontent.com/45185196/134439480-1be7c19b-a634-4885-943b-41169143575a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add 'add'  button to result view
- [ ]  add html and styling for 'list' view
  - [ ] make sure it matches mobile and desktop wireframes; note how on mobile screen everything collapses into 1 column
- [ ] write a 'DOMContentLoaded' and  a 'beforeunload' event handler, so that catch-list information gets stored in localStorage beforeunload and the at load time localStorage is checked for catch list information
- [ ] add handler to 'add' buttons so that on click, the current creature's information, and id number is added to catch list
- [ ]  let user view their catch list by clicking a button to switch to 'list' view
- [ ] each list entry in 'list ' view should have buttons for switching to 'result' view for that creature
- [ ] make page header a button that always switches back to 'find' view
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
